name: Build and Push Docker

on:
  push:
    branches: ["main"]

jobs:
  build:
    uses: Gergo3/nvim-docker-workflows/.github/workflows/docker-build.yml@master
    with:
      image-name: nvim-base
    secrets: inherit

