name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*.*'
      - 'v*.*.*'

permissions:
  contents: write


jobs:
  ci:
    uses: Gergo3/nvim-docker-workflows/.github/workflows/ci.yml@master
    secrets: inherit
